repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 24.3.0
  hooks:
  - id: black
- repo: https://github.com/PyCQA/docformatter
  rev: master
  hooks:
  - id: docformatter
    additional_dependencies: [tomli]
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1
  hooks:
    - id: isort
      additional_dependencies: [toml]
