name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"   

      - name: Install pre-commit >= 4.6.0
        run: pip install "pre-commit>=4.6.0"

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files --show-diff-on-failure --color=always
